### ISSUE TITLE
/usr/bin/tail: cannot open ‘~/file.txt’ for reading: No such file or directory

### ISSUE THREAD

**Issue by chachi** [re5et/itail#1]
"~/" does not get expanded into absolute directory and /usr/bin/tail does not expand it itself.

Calling `expand-file-name` on the passed in file should fix this.

**Comment by re5et** [comment]
Implemented here, should be in melpa shortly.  https://github.com/re5et/itail/commit/e4bc30ab262ee68634c2285511a57bef099e0f55

What tail do you have that doesn't expand the file for you?

**Comment by chachi** [comment]
Thanks! I'm on Ubuntu 14.04 with GNU Coreutils 8.21. The shell will expand "~/" if it's unquoted, but when invoked as `tail -f "<filename>"` no filename expansion seems to occur.
